name: Run Compute

on:
  workflow_dispatch:
  schedule:
  # every day 9 UTC
    - cron:  '0 9 1 1 *'

jobs:
  run-compute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure Python with pip cache
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.x'
        cache: 'pip'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        OPENTRANSIT_S3_BUCKET: opentransit-pdx
        OPENTRANSIT_AGENCY_IDS: trimet
    - name: Install dependencies
      working-directory: backend
      run: |
        pip install -r requirements.txt
    - name: Run compute new
      working-directory: backend
      run: |
        dd=$(date --date='yesterday' +'%Y-%m-%d')
        python compute_new.py --agency=trimet --start-date=$dd
